global:
  scrape_interval:     30s
  evaluation_interval: 60s

scrape_configs:

  - job_name: 'prometheus'
    scrape_interval: 15s
    static_configs:
      - targets:
        - 'prometheus:9090'

  - job_name: 'wordpress'
    scrape_interval: 15s
    metrics_path: /wp-json/prompress/v1/metrics
    static_configs:
      - targets:
        - 'web:80'
    authorization:
      type: Bearer
      credentials: 'abcdef'
